app = "slkc"

[env]
  KC_DB = "postgres"
  KC_DB_URL_HOST = "sldb.internal"
  KC_DB_URL_DATABASE = "keycloak"
  KC_DB_USERNAME = "keycloak"
  KC_HOSTNAME = "id.nullvoid.space"
  KEYCLOAK_ADMIN = "root"
  JAVA_OPTS="-Xms256m -Xmx500m -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=128m -Djava.net.preferIPv4Stack=false"

[build]
  dockerfile = "Dockerfile"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

  [[services.http_checks]]
    interval = 5000
    grace_period = "5s"
    method = "get"
    path = "/realms/master"
    protocol = "http"
    restart_limit = 20
    timeout = 2000
    tls_skip_verify = false
